//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetailsDB
    {
        public int ContractId { get; set; }
        public string ContractType { get; set; }
        public string PickupMode { get; set; }
        public string DateCurrent { get; set; }
        public string ContractDate { get; set; }
        public string ContractBegin { get; set; }
        public string ContractEnd { get; set; }
        public string ContractOpenDays { get; set; }
        public string OwnerName { get; set; }
        public string OwnerBirthday { get; set; }
        public string OwnerAddress { get; set; }
        public string OwnerAddressNo { get; set; }
        public string OwnerTel { get; set; }
        public string RenterName { get; set; }
        public string RenterBirthday { get; set; }
        public string RenterAddress { get; set; }
        public string RenterAddressNo { get; set; }
        public string RenterTel { get; set; }
        public string RentName { get; set; }
        public string RentBirthday { get; set; }
        public string RentAddress { get; set; }
        public string RentTel { get; set; }
        public string ResidentName1 { get; set; }
        public string ResidentBirthday1 { get; set; }
        public string ResidentName2 { get; set; }
        public string ResidentBirthday2 { get; set; }
        public string ResidentName3 { get; set; }
        public string ResidentBirthday3 { get; set; }
        public string Location { get; set; }
        public string LocationName { get; set; }
        public string IssueRoom { get; set; }
        public string HouseNumber { get; set; }
        public string Type { get; set; }
        public string Structure { get; set; }
        public string OuterWall { get; set; }
        public string FloorPlan1 { get; set; }
        public string FloorPlan2 { get; set; }
        public string PakingYesNo { get; set; }
        public string ParkingForm { get; set; }
        public string UsedNumber1 { get; set; }
        public string UsedNumber2 { get; set; }
        public string UsedNumber3 { get; set; }
        public string ParkingLocation { get; set; }
        public string Electricity { get; set; }
        public string CurrentSupplier { get; set; }
        public string Gas { get; set; }
        public string GasType { get; set; }
        public string Supplier { get; set; }
        public string WaterCrew { get; set; }
        public string WaterCrewChoose { get; set; }
        public string WaterTank { get; set; }
        public string WaterTankChoose { get; set; }
        public string Toilet { get; set; }
        public string ToiletChoose { get; set; }
        public string ProcessEquipment { get; set; }
        public string ProcessEquipmentChoose { get; set; }
        public string Sink { get; set; }
        public string SinkChoose { get; set; }
        public string Faucet { get; set; }
        public string FaucetChoose { get; set; }
        public string Kitchen { get; set; }
        public string KitchenChoose { get; set; }
        public string WaterHeater { get; set; }
        public string WaterHeaterChoose { get; set; }
        public string Stove { get; set; }
        public string StoveChoose { get; set; }
        public string Bathroom { get; set; }
        public string BathroomChoose { get; set; }
        public string Shower { get; set; }
        public string ShowerChoose { get; set; }
        public string Reheating { get; set; }
        public string ReheatingChoose { get; set; }
        public string ShowerWith { get; set; }
        public string ShowerWithChoose { get; set; }
        public string Bathtub { get; set; }
        public string BathtubChoose { get; set; }
        public string WashingMachine { get; set; }
        public string WashingMachineChoose { get; set; }
        public string ConnectionBracket { get; set; }
        public string ConnectionBracketChoose { get; set; }
        public string LightingEquipment { get; set; }
        public string LightingEquipmentChoose { get; set; }
        public string LightBulbBall { get; set; }
        public string LightBulbBallChoose { get; set; }
        public string TelevisionAntenna { get; set; }
        public string TelevisionAntennaChoose { get; set; }
        public string FixedTelephone { get; set; }
        public string FixedTelephoneChoose { get; set; }
        public string Phone { get; set; }
        public string PhoneChoose { get; set; }
        public string InternetEquipment { get; set; }
        public string InternetEquipmentChoose { get; set; }
        public string Provider { get; set; }
        public string ProviderChoose { get; set; }
        public string Router { get; set; }
        public string AirConditioning { get; set; }
        public string AirConditioningChoose { get; set; }
        public string Elevator { get; set; }
        public string GarbageStorage { get; set; }
        public string GarbageStorageChoose { get; set; }
        public string Pet { get; set; }
        public string PetChoose { get; set; }
        public string EvacutionLadder { get; set; }
        public string BicycleParkingSpace { get; set; }
        public string DoorPocket { get; set; }
        public string ScreenDoor { get; set; }
        public string FireAlarm { get; set; }
        public string FireExtinguisher { get; set; }
        public string FireHydrant { get; set; }
        public string Storage { get; set; }
        public string StorageChoose { get; set; }
        public string InstallationSunlight { get; set; }
        public string UseNoYes { get; set; }
        public string UseNoYesChoose { get; set; }
        public string HotSpring { get; set; }
        public string HotSpringChoose { get; set; }
        public string OtherBuildings { get; set; }
        public string OtherBuildingsChoose { get; set; }
        public string OtherConditions { get; set; }
        public string OtherConditionsChoose { get; set; }
        public string TransportationFacilities { get; set; }
        public string Rent { get; set; }
        public string CommonServiceFee { get; set; }
        public string CATVFee { get; set; }
        public string ParkingFee { get; set; }
        public string SecurityDeposit { get; set; }
        public string KeyMoney { get; set; }
        public string RentForMonth { get; set; }
        public string CommonServiceFeeMonth { get; set; }
        public string CATVFeeMonth { get; set; }
        public string ParkingFeeMonth { get; set; }
        public string NextMonthFee { get; set; }
        public string RentalInsurancePremium { get; set; }
        public string RentalGuaranteeFee { get; set; }
        public string FeeTaxIncluded { get; set; }
        public string Total { get; set; }
        public Nullable<int> HouseNo { get; set; }
    }
}
