//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDB
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string ImageType { get; set; }
        public string HouseNo { get; set; }
        public string DetachedHouseNo { get; set; }
        public string ApartmentHouseNo { get; set; }
        public string LandNo { get; set; }
    
        public virtual ApartmentDB ApartmentDB { get; set; }
        public virtual DetachedDB DetachedDB { get; set; }
        public virtual RentalManagementDB RentalManagementDB { get; set; }
        public virtual LandDB LandDB { get; set; }
    }
}
