//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandDB()
        {
            this.ImageDB = new HashSet<ImageDB>();
        }
    
        public int LandNo { get; set; }
        public string LandName { get; set; }
        public string LandPost { get; set; }
        public string LandAddress { get; set; }
        public string NearestSation { get; set; }
        public string Price { get; set; }
        public string UnitPrice { get; set; }
        public string LandArea { get; set; }
        public string RoadBurden { get; set; }
        public string LandRights { get; set; }
        public string Ground { get; set; }
        public string CityPlan { get; set; }
        public string UseDistrict { get; set; }
        public string BuildingCoverage { get; set; }
        public string VolumeRaito { get; set; }
        public string OtherLegalRestrictions { get; set; }
        public string Terrain { get; set; }
        public string CurrentSituation { get; set; }
        public string DeliveryConditionTime { get; set; }
        public string BuildingConditions { get; set; }
        public string TransactionMode { get; set; }
        public string RoadsideSituation { get; set; }
        public string Facility { get; set; }
        public string SchoolDistrict { get; set; }
        public string NeighborhoodInformation { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageDB> ImageDB { get; set; }
    }
}
