//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalPaymentDB
    {
        public int RentalPaymentId { get; set; }
        public int HouseNo { get; set; }
        public string HouseName { get; set; }
        public string Rent { get; set; }
        public string RentName { get; set; }
        public string MoneyMonth1 { get; set; }
        public string MoneyMonth1Date { get; set; }
        public string MoneyMonth2 { get; set; }
        public string MoneyMonth2Date { get; set; }
        public string MoneyMonth3 { get; set; }
        public string MoneyMonth3Date { get; set; }
        public string MoneyMonth4 { get; set; }
        public string MoneyMonth4Date { get; set; }
        public string MoneyMonth5 { get; set; }
        public string MoneyMonth5Date { get; set; }
        public string MoneyMonth6 { get; set; }
        public string MoneyMonth6Date { get; set; }
        public string MoneyMonth7 { get; set; }
        public string MoneyMonth7Date { get; set; }
        public string MoneyMonth8 { get; set; }
        public string MoneyMonth8Date { get; set; }
        public string MoneyMonth9 { get; set; }
        public string MoneyMonth9Date { get; set; }
        public string MoneyMonth10 { get; set; }
        public string MoneyMonth10Date { get; set; }
        public string MoneyMonth11 { get; set; }
        public string MoneyMonth11Date { get; set; }
        public string MoneyMonth12 { get; set; }
        public string MoneyMonth12Date { get; set; }
        public string NotPayment { get; set; }
        public string Year { get; set; }
    }
}
