//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalContactDB
    {
        public int HouseNo { get; set; }
        public string HouseName { get; set; }
        public string Rent { get; set; }
        public string ContractDate { get; set; }
        public string RenterName { get; set; }
        public string RenterAddressNo { get; set; }
        public string RenterAddress { get; set; }
        public string RenterPhoneNumber { get; set; }
        public string RenterBirthday { get; set; }
        public string RenterOfficeName { get; set; }
        public string RenterOfficePhone { get; set; }
        public string RentName { get; set; }
        public string RentAddressNo { get; set; }
        public string RentAddress { get; set; }
        public string RentPhoneNumber { get; set; }
        public string RentBirthday { get; set; }
        public string RentOfficeName { get; set; }
        public string RentOfficePhone { get; set; }
        public string JointGuarantorName1 { get; set; }
        public string JointGuarantorAddressNo1 { get; set; }
        public string JointGuarantorAddress1 { get; set; }
        public string JointGuarantorPhone1 { get; set; }
        public string JointGuarantorBirthday1 { get; set; }
        public string JointGuarantorOfficeName1 { get; set; }
        public string JointGuarantorOfficePhone1 { get; set; }
        public string JointGuarantorName2 { get; set; }
        public string JointGuarantorAddressNo2 { get; set; }
        public string JointGuarantorAddress2 { get; set; }
        public string JointGuarantorPhone2 { get; set; }
        public string JointGuarantorBirthday2 { get; set; }
        public string JointGuarantorOfficeName2 { get; set; }
        public string JointGuarantorOfficePhone2 { get; set; }
    }
}
